FROM mhart/alpine-node

WORKDIR /src

ADD . .

ENV NODE_ENV=production
ENV PORT=4000
ENV TRAVELLER_DB_HOST=$MYSQL_PORT_3306_TCP_ADDR
ENV TRAVELLER_DB_DATABASE=$MYSQL_ENV_MYSQL_DATABASE
ENV TRAVELLER_DB_USERNAME=root
ENV TRAVELLER_DB_PASSWORD=$MYSQL_ENV_MYSQL_ROOT_PASSWORD

CMD npm start